version: 2.1
orbs:
  ship: auth0/ship@0.7.2
  codecov: codecov/codecov@3

commands:
  checkout-and-build:
    steps:
      - checkout
      - run: chmod +x gradlew
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew clean build
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
  run-tests:
    steps:
      - run: ./gradlew check jacocoTestReport --continue --console=plain
      - codecov/upload
  run-api-diff:
    steps:
      # run apiDiff task
      - run: ./gradlew apiDiff
      - store_artifacts:
          path: lib/build/reports/apiDiff/apiDiff.txt
      - store_artifacts:
          path: lib/build/reports/apiDiff/apiDiff.html
jobs:
  build:
    docker:
      - image: openjdk:11.0-jdk
    steps:
      - checkout-and-build
      - run-tests
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      TERM: dumb
  api-diff:
    docker:
      - image: openjdk:11.0-jdk
    steps:
      - checkout-and-build
      - run-api-diff
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      TERM: dumb

workflows:
  build-and-test:
    jobs:
      - build
      - ship/java-publish:
          prefix-tag: false
          context:
            - publish-gh
            - publish-sonatype
          filters:
            branches:
              only:
                - master
          requires:
            - build
  api-diff:
    jobs:
      - api-diff
